export const _emailChanged = 'emailChanged'
export const _passwordChanged = 'passwordChanged'
export const _loginSuccess = 'loginSuccess'
export const _loginFailed = 'loginFailed'
export const _login = 'login'
export const _employeeUpdate = 'employeeUpdate'
